### ISSUE TITLE
Проектирование интерфейса приложения

### ISSUE THREAD

**Issue by w3prog** [w3prog/GoodTravelAndroidApp#6]

**Comment by w3prog** [comment]
Есть ли у вас предпочтения к интерфейсу?

**Comment by zmm** [comment]
Конкретного интерфейса, который бы я уже придумал, нет. 
Исходя из структуры проекта - вроде есть все что было бы хорошо иметь (в плане элементов UI), но нет детализации того, как все это будет выглядеть для пользователя. В связи с этим я предлагаю вам составить макет UI приложения (о том как это делать https://hsto.org/files/026/cab/55a/026cab55a5ad4a1daab209c39715b947.png, сервис где это можно сделать - https://app.moqups.com/) и уже его обсуждать.

**Comment by w3prog** [comment]
Разработал прототип приложения дальнейшие размышления по данной проблеме там.
