### ISSUE TITLE
Нужна ли поддержка планшетов?

### ISSUE THREAD

**Issue by w3prog** [w3prog/GoodTravelAndroidApp#7]

**Comment by w3prog** [comment]
Большинство аналогов поддерживают только портретную ориентацию интерфейса.

**Comment by zmm** [comment]
Поддержка дополнительного типа устройств (планшеты, телефоны, ПК ...) всегда будет плюсом, но важно понимать, что это дополнительные усилия на адаптацию и поддержку UI. Однако первостепенной важностью обладает версия для смартфонов, так как у нее больше охват.

**Comment by w3prog** [comment]
Спасибо за ответ
